Vagrant.configure("2") do |config|
  
  config.vm.define "obiettivo" do |obiettivo|
    obiettivo.vm.box = "ubuntu/focal64"
    obiettivo.vm.network "private_network", ip: "192.168.56.10"
  end
  
  config.vm.define "scansionatore" do |scansionatore|
    scansionatore.vm.box = "ubuntu/focal64"
    scansionatore.vm.network "private_network", ip: "192.168.56.11"
  end
end