Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "side1" do |side1|
        side1.vm.hostname = "side1"
        side1.vm.network "private_network", ip: "192.168.56.10"
        side1.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y docker.io
            systemctl start docker
            systemctl enable docker
            usermod -aG docker vagrant
        SHELL
    end

    config.vm.define "side2" do |side2|
        side2.vm.hostname = "side2"
        side2.vm.network "private_network", ip: "192.168.56.11"
        side2.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y docker.io
            systemctl start docker
            systemctl enable docker
            usermod -aG docker vagrant
        SHELL
    end
end
