Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Provisioning to install Docker
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y && apt-get install -y docker.io 
    systemctl start docker
    usermod -aG docker vagrant # Allow the vagrant user to run Docker without sudo
  SHELL

  # Provisioning for the ping-pong script
  config.vm.provision "file", source: "./ping_pong.sh", destination: "/tmp/ping_pong.sh" # Copy ping_pong.sh to the VM
config.vm.provision "shell", inline: <<-SHELL 
    mv /tmp/ping_pong.sh /usr/local/bin/ping_pong.sh 
    chmod +x /usr/local/bin/ping_pong.sh # Make the script executable
    echo "* * * * * /usr/local/bin/ping_pong.sh
  SHELL

  # Node 1
  config.vm.define "node1" do |n| 
    n.vm.hostname = "node1" 
    n.vm.network "private_network", ip: "192.168.56.11"
  end

  # Node 2
  config.vm.define "node2" do |n|
    n.vm.hostname = "node2"
    n.vm.network "private_network", ip: "192.168.56.12" 
  end 
end
