Vagrant.configure("2") do |config|

  config.vm.define "target" do |target|
    target.vm.box = "ubuntu/focal64"
    target.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "scanner" do |scanner|
    scanner.vm.box = "ubuntu/focal64"
    scanner.vm.network "private_network", ip: "192.168.56.11"
  end
end
